# Generated by Django 4.1.5 on 2025-11-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='color',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color_vehiculo',
            field=models.CharField(choices=[('1', 'ROJO'), ('2', 'AZUL'), ('3', 'VERDE')], default='ROJO', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10),
        ),
    ]
